Update Jpip.yml

diff --git a/.github/workflows/Jpip.yml b/.github/workflows/Jpip.yml
--- a/.github/workflows/Jpip.yml
+++ b/.github/workflows/Jpip.yml
@@ -37,10 +37,11 @@ jobs:
           > jp_ips.txt
           while read -r ip; do
             # 调用 API 获取地理位置
-            geo=$(curl -s -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "https://api.ip.sb/geoip/$ip" | jq -r '.country_code' || echo "ERROR")
-            # 如果是日本 IP，保存到 jp_ips.txt 文件，否则输出到控制台
+            response=$(curl -s -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"\"https://api.ip.sb/geoip/$ip")
+            geo=$(echo "$response" | jq -r '.country_code' || echo "ERROR")
+            country=$(echo "$response" | jq -r '.country' || echo "Unknown")            # 如果是日本 IP，保存到 jp_ips.txt 文件，否则输出到控制台
             if [ "$geo" == "JP" ]; then
-              echo "$ip#$geo" >> jp_ips.txt
+              echo "$ip#$country" >> jp_ips.txt
               echo "$ip#$geo"
             elif [ "$geo" == "ERROR" ]; then
               echo "$ip API Error"
